version: '3.8'

services:
  php_app:
    build: .
    image: php:8.0 
    ports:
      - "5200:5200"  
    volumes:
      - .:/app  
    working_dir: /app 
    command: php -S 0.0.0.0:5200 
    restart: unless-stopped
    networks:
      - npm_default
      #  - default

networks:
  npm_default:
    external: true
  # default:

